#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: app1
#spec:
#  replicas: 0
#  selector:
#    matchLabels:
#      app: app1
#  template:
#    metadata:
#      labels:
#        app: app1
#    spec:
#      containers:
#        - name: app1
#          image: app1:1.0
#          ports:
#            - containerPort: 8080
#
#
#
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image:  app2:1.0 # Replace with your service-a image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080