apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002 # Cổng tùy chọn (30000-32767)
  type: NodePort