pipeline {
    agent any
    environment {
            KUBECONFIG = '/var/jenkins_home/.kube/config'
        }

    stages {
        stage('Clone') {
//            steps {
//                 sh '''
//                 git clone https://github.com/vovantung/app1.git
//                 cd app1
//                 git status
//                 '''
//             }
                steps{
                git branch: 'main', url: 'https://github.com/vovantung/app2.git'
                }
        }
        stage('Build app') {
            steps {
               sh '''
                   mvn clean install
               '''
                  }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t app2 .
                docker tag app2:latest 211125364313.dkr.ecr.ap-southeast-1.amazonaws.com/app2:latest
                aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 211125364313.dkr.ecr.ap-southeast-1.amazonaws.com
                docker push 211125364313.dkr.ecr.ap-southeast-1.amazonaws.com/app2:latest
                '''
            }
        }
        stage('Deploy to Minikube') {
            steps {
                sh '''
                    kubectl apply -f deployment.yaml
                '''
            }
        }
    }
}
