pipeline {
    agent any
    environment {
            KUBECONFIG = '/var/jenkins_home/.kube/config'
        }

    stages {
        stage('Clone') {
//            steps {
//                 sh '''
//                 git clone https://github.com/vovantung/app1.git
//                 cd app1
//                 git status
//                 '''
//             }
                steps{
                git branch: 'main', url: 'https://github.com/vovantung/app2.git'
                }
        }
        stage('Build app') {
            steps {
               sh '''
                   mvn clean install
               '''
                  }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t app2:1.0 .
                '''
            }
        }
        stage('Deploy to Minikube') {
            steps {
                sh '''

                    kubectl apply -f deployment2.yaml
                    kubectl apply -f service2.yaml
                '''
            }
        }
    }
}
